---
# Location where configuration files will be stored.
config_dir: '~'

# Enabling OpenVPN client (true/false).
ovpnc_enable: true

# Using second wifi card dongle as AP to TV or TV-box (true/false).
wifi_enable: true
wifi_ssid: "vpntv"              # WiFi network name to connect to.
wifi_password: "Glory2Ukraine!" # You can change it to "HeroiyamSlava!" :)

# Using Ethernet interface as direct connection to TV or TV-box (true/false).
ethernet_enable: false
bridge_subnet: "10.0.90.0/24"