---
# Location where configuration files will be stored.
config_dir: '~'
#    _____ _____ _____                 
#   |  |  |  _  |   | |                
#   |  |  |   __| | | |                
#    \___/|__|  |_|___| 
# Enabling OpenVPN client (true/false).
ovpnclient_enable: true             # You can "false" this line if you already have configured OpenVPN client.
openvpn_external_port: "1194"         # OpenVPN client external port (don't change without purpose)


                                                             
#    _ _ _ _ _____ _    ___    _ _ _ _ _____ _                   
#   | | | |_|   __|_|  |_  |  | | | |_|   __|_|                  
#   | | | | |   __| |  |  _|  | | | | |   __| |                  
#   |_____|_|__|  |_|  |___|  |_____|_|__|  |_|
# Connecting TV to VPNTV own WiFi network while VPNTV connected to WiFi router over your home WiFi.
wifi2wifi_enable: true
wifi_mod_enable: false             # Install custom WiFi modules (don't change without purpose)
wifi_ssid: "vpntv"                 # WiFi network name to connect to.
wifi_password: "Glory2Ukraine!"    # You can change it to "HeroiyamSlava!"
wifi_interface: "wlan1"            # WiFi interface (don't change without purpose)
wifi_channel: "7"                  # WiFi channel (don't change without purpose)

#    _ _ _ _ _____ _    ___    _____ _   _           
#   | | | |_|   __|_|  |_  |  |   __| |_| |_ ___ ___ 
#   | | | | |   __| |  |  _|  |   __|  _|   | -_|  _|
#   |_____|_|__|  |_|  |___|  |_____|_| |_|_|___|_|                                    
# Connecting TV Ethernet to VPNTV Ethernet port, while VPNTV connected to router by home WiFi network.
wifi2ethernet_enable: false
bridge_subnet: "10.0.90.0/24"

#    _____ _   _              ___    _ _ _ _ _____ _ 
#   |   __| |_| |_ ___ ___   |_  |  | | | |_|   __|_|
#   |   __|  _|   | -_|  _|  |  _|  | | | | |   __| |
#   |_____|_| |_|_|___|_|    |___|  |_____|_|__|  |_|
# Connecting TV to VPNTV own WiFi network while VPNTV connected to router by Ethernet cable.
ethernet2wifi_enable: false