---
# Location where configuration files will be stored.
config_dir: '~'
#    _____ _____ _____                 
#   |  |  |  _  |   | |                
#   |  |  |   __| | | |                
#    \___/|__|  |_|___| 
# Enabling OpenVPN client (true/false).
ovpnclient_enable: true             # You can "false" this line if you already have configured OpenVPN client.

#    _ _ _ _ _____ _                   
#   | | | |_|   __|_|                  
#   | | | | |   __| |                  
#   |_____|_|__|  |_| 
# Using USB WiFi card dongle as AP for TV or TV-box (true/false).
wifi_enable: true
wifi_mod_enable: true              # Install custom WiFi modules (don't change without purpose)
wifi_ssid: "vpntv"                 # WiFi network name to connect to.
wifi_password: "Glory2Ukraine!"    # You can change it to "HeroiyamSlava!"
wifi_interface: "wlan1"            # WiFi interface (don't change without purpose)
wifi_channel: "7"                  # WiFi channel (don't change without purpose)

#    _____ _   _                   _   
#   |   __| |_| |_ ___ ___ ___ ___| |_ 
#   |   __|  _|   | -_|  _|   | -_|  _|
#   |_____|_| |_|_|___|_| |_|_|___|_|                                     
# Using internal Ethernet port as direct connection to TV or TV-box (true/false).
ethernet_enable: false
bridge_subnet: "10.0.90.0/24"