---
# Location where configuration files will be stored
config_dir: '~'
#    _____ _           _____             
#   |_   _|_|_____ ___|__   |___ ___ ___ 
#     | | | |     | -_|   __| . |   | -_|
#     |_| |_|_|_|_|___|_____|___|_|_|___|
# Your timezone for all services.
ur_timezone: "Europe/Kyiv"

#    _____ _____ _____                 
#   |  |  |  _  |   | |                
#   |  |  |   __| | | |                
#    \___/|__|  |_|___| 
# Enabling OpenVPN client (true/false)
ovpnclient_enable: true               # Set true or false. You can "false" this line if you already have configured OpenVPN client
openvpn_external_port: "1194"         # OpenVPN client external port (don't change without purpose)

#    _____ _   _              ___    _ _ _ _ _____ _ 
#   |   __| |_| |_ ___ ___   |_  |  | | | |_|   __|_|
#   |   __|  _|   | -_|  _|  |  _|  | | | | |   __| |
#   |_____|_| |_|_|___|_|    |___|  |_____|_|__|  |_|
# Wireless Connection Type 1.
# Connecting TV to VPNTV's new WiFi network while VPNTV connected to your home router Ethernet port
ethernet2wifi_enable: false           # Set true or false
wifi_ssid_t1: "vpntv"                 # WiFi network name to connect to
wifi_password_t1: "Glory2Ukraine!"    # You can change it to "HeroiyamSlava!"
wifi_interface_t1: "wlan0"            # WiFi interface (don't change without purpose)
wifi_channel_t1: "7"                  # WiFi channel (don't change without purpose)

#    _ _ _ _ _____ _    ___    _ _ _ _ _____ _                   
#   | | | |_|   __|_|  |_  |  | | | |_|   __|_|                  
#   | | | | |   __| |  |  _|  | | | | |   __| |                  
#   |_____|_|__|  |_|  |___|  |_____|_|__|  |_|
# Wireless Connection Type 2. 
# Connecting TV to VPNTV's new WiFi network while VPNTV itself connected to your home WiFi network
wifi2wifi_enable: false               # Set true or false
wifi_mod_enable: false                # To install custom RTL WiFi modules (don't change without purpose)
wifi_ssid_t2: "vpntv"                 # WiFi network name to connect to
wifi_password_t2: "Glory2Ukraine!"    # You can change it to "HeroiyamSlava!"
wifi_interface_t2: "wlan1"            # WiFi interface (don't change without purpose)
wifi_channel_t2: "7"                  # WiFi channel (don't change without purpose)

#    _ _ _ _ _____ _    ___    _____ _   _           
#   | | | |_|   __|_|  |_  |  |   __| |_| |_ ___ ___ 
#   | | | | |   __| |  |  _|  |   __|  _|   | -_|  _|
#   |_____|_|__|  |_|  |___|  |_____|_| |_|_|___|_|                                    
# Wired Connection.
# Connecting TV Ethernet to VPNTV's Ethernet port, while VPNTV itself connected to your home WiFi network
wifi2ethernet_enable: false           # Set true or false

#    _____ ___ _____ ___ _____ ___ 
#   | __  |  _|     |   |  |  |  _|
#   |    -|  _| | | | | |  |  |  _|
#   |__|__|___|_|_|_|___|\___/|___|
# VPNTV Configuration remove.
# Removes any Wireless or Wired configuration which was previously done
wifi_config_remove: false             # Set true or false
wifi_module_remove: false             # Set true or false
ovpnclient_remove: false              # Set true or false