---
- name: Install and configure OpenVPN on Raspberry Pi
  hosts: tv-vpn
  become: yes
  
  tasks:

  - name: Ensure apt cache is up to date.
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600
    when:
      - ansible_facts.os_family == "Debian"

  - name: Ensure pacman cache is up to date
    community.general.pacman:
      update_cache: true
    when:
      - ansible_facts.os_family == "Archlinux"
      
  - name: Upgrade packages
    apt:
      upgrade: yes
  
  - name: Install OpenVPN
    apt:
      name: openvpn
      state: present
      
  - name: Copy client.conf to OpenVPN directory
    copy:
      src: ./client-ovpn/client.ovpn
      dest: /etc/openvpn/client.conf
      owner: root
      group: root
      mode: 0600
      
  - name: Enable OpenVPN as a system service
    systemd:
      name: openvpn@client
      state: started
      enabled: yes
      daemon_reload: yes
      unit:
        content: |
          [Unit]
          Description=OpenVPN connection to VPN server
          After=network.target

          [Service]
          Type=forking
          User=root
          Group=root
          WorkingDirectory=/etc/openvpn
          ExecStart=/usr/sbin/openvpn --config /etc/openvpn/client.conf
          Restart=on-failure
          
  - name: Verify OpenVPN service status
    shell: systemctl status openvpn@client
    register: openvpn_status
    
  - name: Display OpenVPN service status
    debug:
      var: openvpn_status.stdout_lines