---
- name: Install and configure OpenVPN client on vpntv
  hosts: vpntv
  become: yes
  
  tasks:
  - name: Debian packages Upgrade
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_facts.os_family == "Debian"
  
  - name: Arch packages Upgrade
    pacman:
      upgrade: yes
    when: ansible_facts.os_family == "Arch"
  
  - name: Debian OpenVPN Installation
    apt:
      name: openvpn
      state: present
    when: ansible_facts.os_family == "Debian"
    
  - name: Arch OpenVPN Installation
    pacman:
      name: openvpn
      state: present
    when: ansible_facts.os_family == "Arch"
      
  - name: Copy client.ovpn as client.conf to OpenVPN directory
    copy:
      src: ./client-ovpn/client.ovpn
      dest: /etc/openvpn/client.conf
      owner: root
      group: root
      mode: 0600
      
  - name: Ensure OpenVPN service unit file exists
    become: yes
    lineinfile:
      dest: /etc/systemd/system/openvpn@.service
      line: |
        [Unit]
        Description="OpenVPN connection to VPN server"
        Wants=network-online.target
        After=network.target
  
        [Service]
        Type=forking
        User=root
        Group=root
        WorkingDirectory=/etc/openvpn
        ExecStart=/usr/sbin/openvpn --config /etc/openvpn/client.conf
        Restart=on-failure
    when: ansible_facts.os_family == "Debian"

  - name: Enable OpenVPN service
    become: yes
    systemd:
      name: openvpn@.service
      state: started
      enabled: yes
      daemon_reload: yes
    when: ansible_facts.os_family == "Debian"
    
  - name: Enable OpenVPN as a system service in Arch
    systemd:
      name: openvpn@.service
      state: started
      enabled: yes
      daemon_reload: yes
      unit:
        content: |
          [Unit]
          Description=OpenVPN connection to VPN server
          After=network.target
          Wants=network-online.target

          [Service]
          Type=forking
          User=root
          Group=root
          WorkingDirectory=/etc/openvpn
          ExecStart=/usr/bin/openvpn --config /etc/openvpn/client.conf
          Restart=on-failure
    when: ansible_facts.os_family == "Arch"
    
#  - name: Reload systemd to use OpenVPN service configuration for Debian
#    shell: systemctl daemon-reload
#    when: ansible_facts.os_family == "Debian"
    
  - name: Verify OpenVPN service status for Arch
    shell: systemctl status openvpn@client
    register: openvpn_status
    when: ansible_facts.os_family == "Arch"
    
  - name: Verify OpenVPN service status in Debian
    shell: systemctl status openvpn@client
    register: openvpn_status
    when: ansible_facts.os_family == "Debian"