---
- name: Install and configure OpenVPN client on vpntv
  hosts: vpntv
  become: 'yes'

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml

    - name: Debian packages Upgrade
      apt:
        upgrade: 'yes'
        update_cache: 'yes'
        cache_valid_time: '3600'
      when: ansible_facts.os_family == 'Debian'

    - name: Arch packages Upgrade
      pacman:
        upgrade: 'yes'
      when: ansible_facts.os_family == 'Arch'

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Configuring OpenVPN client
      ansible.builtin.import_tasks: tasks/ovpn-client.yml
      when: ovpnclient_enable

    - name: Installing WiFi dongle modules
      ansible.builtin.import_tasks: tasks/wifi-modules.yml
      when: wifi_mod_enable

    - name: Wireless Connection Type 1. TV WiFi to VPNTV WiFi
      ansible.builtin.import_tasks: tasks/config-wifi2wifi.yml
      when: wifi2wifi_enable

# This Part not completed yet:
#    - name: Wireless Connection Type 2. TV WiFi to VPNTV Ethernet
#      ansible.builtin.import_tasks: tasks/config-eth2wifi.yml
#      when: ethernet2wifi_enable

#    - name: Wired Connection. TV Ethernet to VPNTV Ethernet port
#      ansible.builtin.import_tasks: tasks/config-wifi2eth.yml
#      when: wifi2ethernet_enable
