---
- name: Install and configure OpenVPN client on tv-vpn
  hosts: tv-vpn
  become: yes
  
  tasks:
  - name: Upgrade packages Debian
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_facts.os_family == "Debian"
  
  - name: Upgrade packages Arch
    pacman:
      upgrade: yes
    when: ansible_facts.os_family == "Arch"
  
  - name: Install OpenVPN Debian
    apt:
      name: openvpn
      state: present
    when: ansible_facts.os_family == "Debian"
    
  - name: Install OpenVPN Arch
    pacman:
      name: openvpn
      state: present
    when: ansible_facts.os_family == "Arch"
      
  - name: Copy client.conf to OpenVPN directory
    copy:
      src: ./client-ovpn/client.ovpn
      dest: /etc/openvpn/client.conf
      owner: root
      group: root
      mode: 0600
      
  - name: Enable OpenVPN as a system service Debian
    systemd:
      name: openvpn@client
      state: started
      enabled: yes
      daemon_reload: yes
      unit:
        content: |
          [Unit]
          Description=OpenVPN connection to VPN server
          Wants=network-online.target
          After=network.target

          [Service]
          Type=forking
          User=root
          Group=root
          WorkingDirectory=/etc/openvpn
          ExecStart=/usr/sbin/openvpn --config /etc/openvpn/client.conf
          Restart=on-failure
    when: ansible_facts.os_family == "Debian"
    
  - name: Enable OpenVPN as a system service Arch
    systemd:
      name: openvpn@client
      state: started
      enabled: yes
      daemon_reload: yes
      unit:
        content: |
          [Unit]
          Description=OpenVPN connection to VPN server
          After=network.target
          Wants=network-online.target

          [Service]
          Type=forking
          User=root
          Group=root
          WorkingDirectory=/etc/openvpn
          ExecStart=/usr/bin/openvpn --config /etc/openvpn/client.conf
          Restart=on-failure
    when: ansible_facts.os_family == "Arch"
    
  - name: Reload systemd to use OpenVPN service configuration Debian
    shell: systemctl daemon-reload
    when: ansible_facts.os_family == "Debian"
    
  - name: Verify OpenVPN service status Arch
    shell: systemctl status openvpn@client
    register: openvpn_status
    when: ansible_facts.os_family == "Arch"
    
  - name: Verify OpenVPN service status Debian
    shell: systemctl status openvpn@client
    register: openvpn_status
    when: ansible_facts.os_family == "Debian"