---
- name: Install and configure udhcpd, hostapd, dnsmasq, and ufw on Debian
  become: yes
  apt:
    name: 
    - udhcpd
    - dnsmasq
    - hostapd
    - ufw
    state: present
  when: ansible_facts.os_family == 'Debian'

- name: Install and configure udhcpd, hostapd, dnsmasq, and ufw on Arch
  become: yes
  pacman:
    name: 
    - udhcpd
    - dnsmasq
    - hostapd
    - ufw
    state: present
  when: ansible_facts.os_family == 'Arch'

- name: Enable and start ufw
  become: yes
  service:
    name: ufw
    state: started
    enabled: yes

- name: Add OpenVPN POSTROUTNG rules to UFW
  become: yes
  blockinfile:
    path: /etc/ufw/before.rules
    block: |
      # START OPENVPN RULES
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -s 10.0.90.0/24 -o wlan1 -j MASQUERADE
      COMMIT
    marker: "# START OPENVPN RULES"
  notify:
    - restart ufw

- name: Allow incoming traffic on wlan1 for port 67 (UDP)
  become: yes
  ufw:
    rule: allow
    direction: in
    interface: wlan1
    port: '67'
    proto: udp
    
- name: Allow incoming traffic on wlan1 for port 53 (UDP)
  become: yes
  ufw:
    rule: allow
    direction: in
    interface: wlan1
    port: '53'
    proto: udp

- name: Add static IP address configuration for wlan1 interface
  become: yes
  lineinfile:
    dest: /etc/dhcpcd.conf
    line: |
      interface wlan1
      static ip_address=10.0.90.1/24
      nohook wpa_supplicant
    insertafter: "^# interface wlan1"
    state: present
  notify:
    - restart dhcpcd

- name: Copy dnsmasq configuration file to backup location
  become: yes
  copy:
    src: /etc/dnsmasq.conf
    dest: /etc/dnsmasq.conf.bak

- name: Create new dnsmasq configuration file
  become: yes
  lineinfile:
    dest: /etc/dnsmasq.conf
    line: |
      interface=wlan1 # Listening interface
      dhcp-range=10.0.90.2,10.0.90.25,255.255.255.0,24h
                    # Pool of IP addresses served via DHCP
      domain=wlan   # Local wireless DNS domain
      address=/gw.wlan/10.0.90.1
                    # Alias for this router
    insertafter: "^# interface=wlan1 # Listening interface"
    state: present
  notify:
    - restart dnsmasq

- name: Copy hostapd configuration file
  become: yes
  copy:
    src: ./templates/hostapd.conf.yaml
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart hostapd