---
- name: Install and configure dnsmasq, hostapd and iptables-persistent on Debian
  become: yes
  apt:
    name: 
    - dnsmasq
    - hostapd
    - iptables-persistent
    - netfilter-persistent
    state: present
  when: ansible_facts.os_family == 'Debian'

- name: Install and configure dnsmasq, hostapd and iptables-persistent on Arch
  become: yes
  pacman:
    name: 
    - dnsmasq
    - hostapd
    - iptables-persistent
    - netfilter-persistent
    state: present
  when: ansible_facts.os_family == 'Arch'

- name: Unmask hostapd
  become: yes
  command: systemctl unmask hostapd

- name: Copy templated hostapd config into a place.
  become: yes
  ansible.builtin.template:
    src: ./templates/hostapd.conf.yaml
    dest: "/etc/hostapd/hostapd.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart hostapd

- name: Start and enable hostapd service
  become: yes
  systemd:
    name: hostapd
    state: started
    enabled: yes

- name: Enable IP Forwarding Configuration
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1'
    line: 'net.ipv4.ip_forward=1'

- name: Immedeately apply IP Forwarding
  become: yes
  shell: |
    echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Check vpntv wifi iptables rules were already applied
  become: yes
  lineinfile:
    state: absent
    dest: /etc/iptables/rules.v4
    regexp: "^# VPNTV OPENVPN RULES"
  check_mode: true
  changed_when: false
  register: iptables_vpntv_rules_check

- name: Copy templated iptables persistent rules into a place.
  become: yes
  ansible.builtin.template:
    src: ./templates/ipt-rules.v4.yaml
    dest: "/etc/iptables/rules.v4"
    owner: root
    group: root
    mode: 0644
  when: iptables_vpntv_rules_check.found == 0
  notify:
    - Reload iptables rules

- name: Check vpntv dhcpcd static IP configuration was already done
  become: yes
  lineinfile:
    state: absent
    dest: /etc/dhcpcd.conf
    regexp: "^# VPNTV DHCPCD RULES"
  check_mode: true
  changed_when: false
  register: dhcpcd_vpntv_rules_check

- name: Add vpntv dhcpcd static IP configuration
  become: yes
  lineinfile:
    state: present
    path: /etc/dhcpcd.conf
    line: "\n# VPNTV DHCPCD RULES\ninterface wlan1\n    static ip_address=10.0.90.1/24\n    nohook wpa_supplicant\ndenyinterfaces wlan1\n#VPNTV CONF END"
    backup: yes
  when: dhcpcd_vpntv_rules_check.found == 0
  notify:
    - restart dhcpcd

- name: Check vpntv dnsmasq configuration was already done
  become: yes
  lineinfile:
    state: absent
    dest: /etc/dnsmasq.conf
    regexp: "^# VPNTV DNSMASQ RULES"
  check_mode: true
  changed_when: false
  register: dnsmasq_vpntv_rules_check

- name: Add vpntv dnsmasq configuration
  become: yes
  lineinfile:
    state: present
    path: /etc/dnsmasq.conf
    line: "\n# VPNTV DNSMASQ RULES\ninterface=wlan1\ndhcp-range=10.0.90.2,10.0.90.25,255.255.255.0,24h\n#VPNTV CONF END"
    backup: yes
  when: dnsmasq_vpntv_rules_check.found == 0
  notify:
    - restart dnsmasq