---
- name: Install and configure udhcpd, dnsmasq, and ufw on Debian
  become: yes
  apt:
    name: 
    - udhcpd
    - dnsmasq
    - ufw
    state: present
  when: ansible_facts.os_family == 'Debian'

- name: Install and configure udhcpd, dnsmasq, and ufw on Arch
  become: yes
  pacman:
    name: 
    - udhcpd
    - dnsmasq
    - ufw
    state: present
  when: ansible_facts.os_family == 'Arch'