---
- name: Install and configure udhcpd, hostapd, dnsmasq, and ufw on Debian
  apt:
    name: 
    - udhcpd
    - dnsmasq
    - hostapd
    - ufw
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install and configure udhcpd, hostapd, dnsmasq, and ufw on Arch
  pacman:
    name: 
    - udhcpd
    - dnsmasq
    - hostapd
    - ufw
    state: present
  when: ansible_facts.os_family == "Arch"

- name: Allow incoming traffic on wlan1 for port 53 (UDP)
   ufw:
     rule: allow
     direction: incoming
     interface: wlan1
     port: 53/udp
     proto: udp

- name: Allow incoming traffic on wlan1 for port 67 (UDP)
  ufw:
    rule: allow
    direction: incoming
    interface: wlan1
    port: 67/udp
    proto: udp

- name: Add OpenVPN POSTROUTNG rules to UFW
  hosts: all
  become: yes
  tasks:
    - name: Add OpenVPN rules to UFW
      lineinfile:
        path: /etc/ufw/before.rules
        insertafter: "# START OPENVPN RULES"
        line: |
          *nat
          :POSTROUTING ACCEPT [0:0]
          -A POSTROUTING -s 10.0.90.0/24 -o wlan1 -j MASQUERADE
          COMMIT
      notify:
        - restart ufw

handlers:
   - name: restart ufw
     service:
       name: ufw
       state: restarted


