---
    - name: Debian OpenVPN-client Installation
      become: yes
      apt:
        name: openvpn
        state: present
      when: ansible_facts.os_family == "Debian"

    - name: Arch OpenVPN-client Installation
      pacman:
        name: openvpn
        state: present
      when: ansible_facts.os_family == "Arch"
        
    - name: Copy client.conf to OpenVPN directory
      copy:
        src: ./client-ovpn/client.ovpn
        dest: /etc/openvpn/client/client.conf
        owner: root
        group: root
        mode: 0644

    - name: Copy openvpn@.service to systemd directory
      become: yes
      copy:
        src: ./templates/openvpn@.service.yaml
        dest: /etc/systemd/system/openvpn@.service
        owner: root
        group: root
        mode: 0644

#    - name: Create OpenVPN client service unit file
#      become: yes
#      file:
#        path: /etc/systemd/system/openvpn@.service
#        state: touch

#    - name: Create OpenVPN client service configuration
#      become: yes
#      lineinfile:
#        dest: /etc/systemd/system/openvpn@.service
#        line: |
#          [Unit]
#          Description=OpenVPN client connection to %i
#          Wants=network-online.target
#          After=network-online.target

#          [Service]
#          PrivateTmp=yes
#          User=root
#          ExecStart=/usr/sbin/openvpn --config /etc/openvpn/client/%i.conf

#          [Install]
#          WantedBy=multi-user.target
#        state: present
#        create: yes

    - name: Enable OpenVPN service
      become: yes
      systemd:
        name: openvpn-client@client.service
        state: started
        enabled: yes
        daemon_reload: yes
      
    - name: Reload systemd to use OpenVPN service configuration
      become: yes
      shell: systemctl daemon-reload

#    - name: Verify OpenVPN service status
#      become: yes
#      shell: systemctl status openvpn-client@client.service
#      register: openvpn_status  