---
 - name: Make Wi-Fi module installation script executable
   become: yes
   file:
     path: ./wifi-modules/8188eu-install.sh
     mode: 0755
    
 - name: Run Wi-Fi module installation script
   become: yes
   shell: ./wifi-modules/8188eu-install.sh
   notify:
     - restart etworking