---
- name: Check if module 8188eu is loaded
  become: yes
  shell: lsmod | grep -q 8188eu
  register: lsmod_result
  ignore_errors: yes

- name: Copy blacklist-r8188eu.conf to /etc/modprobe.d/
  become: yes
  become_user: root
  copy:
    src: ./templates/blacklist-r8188eu.conf.yaml
    dest: /etc/modprobe.d/blacklist-r8188eu.conf
    owner: root
    group: root
    mode: 0644

- name: Unload the r8188eu module
  become: yes
  command: rmmod r8188eu
  when: lsmod_result != 0
  ignore_errors: yes
  notify:
    - restart networking

- name: Make Wi-Fi module installation script executable
  become: yes
  when: lsmod_result != 0
  file:
    path: ./wifi-modules/8188eu-install.sh
    mode: 0755 
    
- name: Run Wi-Fi module installation script
  become: yes
  when: lsmod_result != 0
  shell: ./wifi-modules/8188eu-install.sh
  notify:
    - restart networking

- name: Check result of module loading
  debug:
    msg: "Module 8188eu already loaded. Nothing to do!"
  when: lsmod_result == 0
