---
- name: Install Wi-Fi module and restart server
  hosts: localhost
  become: yes
  tasks:
    - name: Run Wi-Fi module installation script
      shell: ../wifi-modules/8188eu-install.sh

    - name: Restart server
      service:
        name: networking
        state: restarted